In [9]:
import numpy as np

**dot()** product of two arrays. If both arrays are 1-dimensional arrays, the **dot()** function performs the inner product of vectors. But arrays has to be created as **numpy arrays**

In [10]:
array1=[1,2,3,4]
array2=[1,2,3,4]

In [11]:
new_np_array1=np.array(array1)
new_np_array2=np.array(array2)
type(new_np_array1)

numpy.ndarray

In [12]:
np.dot(new_np_array1,new_np_array2)

30

In [13]:
(new_np_array1*new_np_array2).sum()

30

In [14]:
new_np_array2.sum()

10

================================================================

**NumPy** operations and functions are implemented internally in **C++**, which makes numPy much faster than Python statements and loops which are interpreted at runtime.

In [15]:
%%time
arr1= list(range(1000000))
arr2= list(range(1000000,2000000))

array1_np=np.array(arr1)
array2_np=np.array(arr2)
print(array1_np,array2_np)

[     0      1      2 ... 999997 999998 999999] [1000000 1000001 1000002 ... 1999997 1999998 1999999]
CPU times: total: 203 ms
Wall time: 206 ms


In [16]:
%%time
result=0

for x,y in zip(arr1,arr2):
    result += x*y
result

CPU times: total: 234 ms
Wall time: 215 ms


833332333333500000

In [17]:
%%time
np.dot(array1_np,array2_np)

CPU times: total: 0 ns
Wall time: 2 ms


-1942957984

===========================================================================

#### 3-dimensional arrays

In [18]:
one_d_array=[12,45,78]

In [19]:
# 1-D array (vector)
one_d_array

[12, 45, 78]

In [20]:
climate_data=np.array([
    [45,65,78],
    [78,45,11],
    [14,74,64],
])

In [21]:
# 2-D array (matrix)
climate_data.shape

(3, 3)

In [22]:
three_d_array=np.array([
    [
        [12,45,78],
        [41,52,63],
        [32,65,98]
    ],
    [
        [78,45,12],
        [87,45,12],
        [22,11,33]
    ],
    [
        [10,45,20],
        [80,1,8],
        [64,41,54]
    ]
])

In [23]:
three_d_array.shape

(3, 3, 3)

In [24]:
print(one_d_array)
print('=====================')
print(climate_data)
print('=====================')
print(three_d_array)

[12, 45, 78]
[[45 65 78]
 [78 45 11]
 [14 74 64]]
[[[12 45 78]
  [41 52 63]
  [32 65 98]]

 [[78 45 12]
  [87 45 12]
  [22 11 33]]

 [[10 45 20]
  [80  1  8]
  [64 41 54]]]


==========================================================================

multiplication by using **matmul()** method

In [25]:
np.matmul(one_d_array, climate_data)

array([5142, 8577, 6423])

In [26]:
results = one_d_array @ three_d_array

In [29]:
results

array([[ 4485,  7950, 11415],
       [ 6567,  3423,  3258],
       [ 8712,  3783,  4812]])

===========================================================================

**NumPy** provides hundreds of functions for performing operations on arrays. Some common functions:

* Math: **np.sum**, **np.exp**, **np.round**, arithmetic operators
* Array manipulation: **np.reshape**, **np.stack**, **np.concatenate**, **np.split**
* Linear algebra: **np.matmul**, **np.dot**, **np.transpose**, **np.eigvals**
* Statistics: **np.mean**, **np.median**, **np.std**, **np.max**

In [33]:
results

array([[ 4485,  7950, 11415],
       [ 6567,  3423,  3258],
       [ 8712,  3783,  4812]])

In [34]:
three_d_array

array([[[12, 45, 78],
        [41, 52, 63],
        [32, 65, 98]],

       [[78, 45, 12],
        [87, 45, 12],
        [22, 11, 33]],

       [[10, 45, 20],
        [80,  1,  8],
        [64, 41, 54]]])

======================================================================

**Broadcasting** is summing up two arrays. Smaller arrays **columns** should match larger arrays when multiplying them

In [35]:
results + three_d_array

array([[[ 4497,  7995, 11493],
        [ 6608,  3475,  3321],
        [ 8744,  3848,  4910]],

       [[ 4563,  7995, 11427],
        [ 6654,  3468,  3270],
        [ 8734,  3794,  4845]],

       [[ 4495,  7995, 11435],
        [ 6647,  3424,  3266],
        [ 8776,  3824,  4866]]])

In [44]:
three_d_array

array([[[12, 45, 78],
        [41, 52, 63],
        [32, 65, 98]],

       [[78, 45, 12],
        [87, 45, 12],
        [22, 11, 33]],

       [[10, 45, 20],
        [80,  1,  8],
        [64, 41, 54]]])

In [40]:
three_d_array[1,2,1]

11

In [48]:
experimentation_arr = np.array([
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
    [50,51,52,53,54,55]
])

In [49]:
experimentation_arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [50]:
experimentation_arr[0,2:4]

array([2, 3])

In [51]:
experimentation_arr[4:,4:]

array([[44, 45],
       [54, 55]])

In [52]:
experimentation_arr[:,3]

array([ 3, 13, 23, 33, 43, 53])

In [60]:
experimentation_arr[0::2,1::2]

array([[ 1,  3,  5],
       [21, 23, 25],
       [41, 43, 45]])

In [78]:
experimentation_arr.shape

(44,)

=========================================================================

to reshape any array values goes like this:

.reshape(arrays * rows * columns). **Shape** number must match reshape numbers multiplied

In [79]:
experimentation_arr.reshape(2,11,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]],

       [[22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43]]])